"use strict";
document.addEventListener('DOMContentLoaded', function () {
    var appWindow = document.getElementById('settings-app-window');
    appWindow.style.minHeight = '400px';
    appWindow.style.minWidth = '600px';
    var appWindowBody = appWindow.children[1];
    function createCategory(name) {
        var category = document.createElement('div');
        category.classList.add('category');
        category.id = name + '-category';
        category.textContent = name;
        category.style.color = 'white';
        category.style.fontSize = '12px';
        category.style.fontWeight = 'bold';
        category.style.width = '150px';
        category.style.height = 'auto';
        category.style.margin = '10px auto';
        category.style.display = 'grid';
        category.style.gridTemplateColumns = '1fr auto';
        category.style.gridAutoFlow = 'dense';
        category.style.justifyContent = 'space-between';
        category.style.position = 'relative';
        category.style.padding = '0 10px';
        category.style.boxSizing = 'border-box';
        category.style.transition = 'background-color 0.2s ease';
        category.style.left = '0px';
        category.style.top = '40px';
        category.addEventListener('mouseenter', function () {
            category.style.backgroundColor = 'rgb(100, 105, 235)';
        });
        category.addEventListener('mouseleave', function () {
            category.style.backgroundColor = 'transparent';
        });
        category.style.textAlign = 'center';
        category.style.lineHeight = '40px';
        var isOpen = false;
        var icon = document.createElement('img');
        category.appendChild(icon);
        icon.src = './img/Control_Panel_XP.png';
        icon.style.width = '40px';
        icon.style.height = '40px';
        icon.style.marginRight = '5px';
        icon.style.userSelect = 'none';
        icon.style.pointerEvents = 'none';
        category.insertBefore(icon, category.firstChild);
        rightColumn.appendChild(category);
        return category;
    }
    var appContent = document.createElement('div');
    appContent.id = 'settings-app-content';
    appContent.style.width = '100%';
    appContent.style.height = '100%';
    appContent.style.backgroundColor = 'rgba(0, 0, 0, 0.25)';
    appContent.style.display = 'auto';
    var appHeader = document.createElement('div');
    appHeader.id = 'setting-app-header';
    appContent.appendChild(appHeader);
    appHeader.style.width = '100%';
    appHeader.style.height = '50px';
    appHeader.style.background = 'rgb(255, 244, 209)';
    appHeader.style.display = 'block';
    appHeader.style.position = 'relative';
    appHeader.style.boxSizing = 'border-box';
    appHeader.style.top = '0px';
    appHeader.style.left = '0px';
    appHeader.style.overflow = 'hidden';
    var OptionContainer = document.createElement('div');
    appHeader.appendChild(OptionContainer);
    OptionContainer.id = 'settings-app-header-options';
    OptionContainer.style.width = '100%';
    OptionContainer.style.height = '35%';
    OptionContainer.style.background = 'rgb(255, 244, 209)';
    OptionContainer.style.display = 'block';
    OptionContainer.style.position = 'relative';
    OptionContainer.style.top = '0px';
    OptionContainer.style.left = '0px';
    OptionContainer.style.overflow = 'hidden';
    OptionContainer.style.display = 'flex';
    OptionContainer.style.justifyContent = 'left';
    OptionContainer.style.backgroundColor = 'rgba(255, 0, 0, 0.38)';
    function createAppHeaderOptions(name) {
        var option = document.createElement('div');
        option.classList.add('app-header-option');
        OptionContainer.appendChild(option);
        option.id = 'settings-app-' + name + '-option';
        option.textContent = name;
        option.style.color = 'black';
        option.style.fontSize = '12px';
        option.style.width = 'auto';
        option.style.height = 'fit-content';
        option.style.top = '0px';
        option.style.left = '5px';
        option.style.margin = '2px 0px';
        option.style.display = 'flex';
        option.style.justifyContent = 'left';
        option.style.alignItems = 'center';
        option.style.flexDirection = 'column';
        option.style.position = 'relative';
        option.style.padding = '0 5px';
        option.addEventListener('mouseenter', function () {
            option.style.backgroundColor = 'rgb(193, 191, 183)';
            // option.style.color = 'white';
        });
        option.addEventListener('mouseleave', function () {
            option.style.backgroundColor = 'transparent';
            // option.style.color = 'black';
        });
    }
    createAppHeaderOptions('File');
    createAppHeaderOptions('Edit');
    createAppHeaderOptions('View');
    createAppHeaderOptions('Favorites');
    createAppHeaderOptions('Tools');
    createAppHeaderOptions('Help');
    var ButtonContainer = document.createElement('div');
    appHeader.appendChild(ButtonContainer);
    ButtonContainer.style.width = '100%';
    ButtonContainer.style.height = '65%';
    ButtonContainer.style.display = 'flex';
    ButtonContainer.style.justifyContent = 'left';
    ButtonContainer.style.position = 'absolute';
    ButtonContainer.style.top = '35%';
    ButtonContainer.style.left = 'auto';
    ButtonContainer.style.overflow = 'hidden';
    ButtonContainer.style.flexDirection = 'initial';
    ButtonContainer.style.padding = '0 2px';
    ButtonContainer.style.boxSizing = 'border-box';
    ButtonContainer.style.backgroundColor = 'rgba(55, 255, 0, 0.27)';
    function createButton(img) {
        var Button = document.createElement('img');
        ButtonContainer.appendChild(Button);
        Button.src = './img/Settings_app/back-icon.png';
        Button.style.width = '20px';
        Button.style.height = '20px';
        Button.style.position = 'relative';
        Button.style.top = "calc(50% - ".concat(Button.style.height, ")");
        Button.style.left = '0px';
        Button.style.cursor = 'pointer';
        Button.style.overflow = 'hidden';
        Button.style.padding = '0 5px';
        Button.addEventListener('mouseenter', function () {
            Button.style.filter = 'brightness(1.2)';
        });
        Button.addEventListener('mouseleave', function () {
            Button.style.filter = 'brightness(1)';
        });
        return Button;
    }
    var backButton = createButton('./img/Settings_app/back-icon.png');
    var forwardButton = createButton('./img/Settings_app/back-icon.png');
    forwardButton.style.transform = 'scaleX(-1)';
    var leftColumn = document.createElement('div');
    appContent.appendChild(leftColumn);
    leftColumn.style.position = 'relative';
    leftColumn.style.top = '0px';
    leftColumn.style.width = '35%';
    leftColumn.style.minWidth = '200px';
    leftColumn.style.maxWidth = '400px';
    leftColumn.style.height = '100%';
    leftColumn.style.float = 'left';
    leftColumn.style.background = 'linear-gradient(to bottom, rgb(117, 142, 219), rgb(109, 124, 218), rgb(104, 108, 213))';
    var leftColumnMenus = document.createElement('img');
    leftColumn.appendChild(leftColumnMenus);
    leftColumnMenus.src = './img/xp_controlpanel_left_cmp.png';
    leftColumnMenus.style.width = '90%';
    leftColumnMenus.style.height = 'auto';
    leftColumnMenus.style.margin = '10px auto';
    leftColumnMenus.style.display = 'block';
    leftColumnMenus.style.position = 'relative';
    leftColumnMenus.style.padding = '0 10px';
    leftColumnMenus.style.userSelect = 'none';
    leftColumnMenus.style.pointerEvents = 'none';
    var rightColumn = document.createElement('div');
    appContent.appendChild(rightColumn);
    rightColumn.style.width = '65%';
    rightColumn.style.height = '100%';
    rightColumn.style.float = 'left';
    rightColumn.style.display = 'grid';
    rightColumn.style.gridTemplateColumns = 'repeat(auto-fill, 150px)';
    rightColumn.style.gridAutoFlow = 'dense';
    rightColumn.style.justifyContent = 'space-between';
    rightColumn.style.position = 'relative';
    rightColumn.style.padding = '0 10px';
    rightColumn.style.boxSizing = 'border-box';
    rightColumn.style.overflowX = 'scroll';
    rightColumn.style.overflowY = 'scroll';
    rightColumn.style.backgroundColor = 'rgba(88, 93, 223, 0.78)';
    var rightColumnTitle = document.createElement('div');
    rightColumn.appendChild(rightColumnTitle);
    rightColumnTitle.textContent = 'Pick a category';
    rightColumnTitle.style.color = 'rgba(212, 206, 255, 0.9)';
    rightColumnTitle.style.fontSize = '30px';
    rightColumnTitle.style.fontWeight = 'bold';
    rightColumnTitle.style.width = '400px';
    rightColumnTitle.style.height = '80px';
    rightColumnTitle.style.margin = '10px auto';
    rightColumnTitle.style.textAlign = 'left';
    rightColumnTitle.style.position = 'relative';
    rightColumnTitle.style.padding = '0 10px';
    rightColumnTitle.style.boxSizing = 'border-box';
    rightColumnTitle.style.top = '20px';
    rightColumnTitle.style.left = '20px';
    var Appearance = createCategory('Appearance');
    var Personalization = createCategory('Personalization');
    var UserAccount = createCategory('User Account');
    var Network = createCategory('Network');
    var Hardware = createCategory('Hardware');
    var System = createCategory('System');
    var Security = createCategory('Security');
    var DateAndTime = createCategory('Date and Time');
    var Accessibility = createCategory('Accessibility');
    var Speech = createCategory('Speech');
    var Privacy = createCategory('Privacy');
    appWindow.children[1].appendChild(appContent);
});
