services:
  postgres:
    build:
      context: ./db/pgSQL
    container_name: postgres_container
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    build:
      context: ./db/pgAdmin
    container_name: pgadmin_container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    env_file: .env
    restart: always

  djangoapp : 
    build: 
      context : ./backend/project/
    container_name: django_container
    depends_on:
      - postgres
    volumes:
      - ./backend/project:/app
    env_file: .env
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:
  pgadmin_data:


