global:
  scrape_interval: 15s # Adjust if needed
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "djangoapp"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["djangoapp:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch_exporter:9114"]
