apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    inputName: DS_PROMETHEUS
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheusdatasource
