global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch_exporter:9114"]

  - job_name: "fastify"
    static_configs:
      - targets: ["fastifyapp:4321"]
