global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - './alert_rules.yml'

alerting:
  alertmanagers:
    - scheme: https
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets:
            - 'alertmanager:9093'


scrape_configs:
  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch_exporter:9114"]

  - job_name: "fastify"
    static_configs:
      - targets: ["fastifyapp:4321"]

  - job_name: "prometheus"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
