#BASIC
server.host: "0.0.0.0"
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: ["config/certs/ca/ca.crt"]

#Xpack
xpack.security.encryptionKey: ${ENCRYPTION_KEY}
xpack.encryptedSavedObjects.encryptionKey: ${ENCRYPTION_KEY}
xpack.reporting.encryptionKey: ${ENCRYPTION_KEY}


#SSL
server.ssl.enabled: true
server.ssl.certificate: config/certs/ca/ca.crt
server.ssl.key: config/certs/ca/ca.key

monitoring.ui.container.elasticsearch.enabled: true

